Update Containerfile-1

diff --git a/Containerfile-1 b/Containerfile-1
--- a/Containerfile-1
+++ b/Containerfile-1
@@ -1,5 +1,10 @@
 # syntax=docker/dockerfile:1
+
+########################################
+# Этап 1: builder
+########################################
 FROM almalinux:9 AS builder
+
 ARG PG_BABEL_TAG=BABEL_5_4_0__PG_17_7
 ARG EXT_BABEL_TAG=BABEL_5_4_0
 ARG ANTLR_VERSION=4.13.2
@@ -7,65 +12,154 @@ ARG CMAKE_VERSION=3.28.3
 ARG POSTGIS_VERSION=3.5.1
 ARG TDS_FDW_VERSION=2.0.4
 
-RUN dnf install -y epel-release && dnf config-manager --set-enabled crb && dnf install -y gcc gcc-c++ make flex bison libicu-devel libxml2-devel openssl-devel libuuid-devel readline-devel zlib-devel python3-devel perl perl-core perl-devel perl-IPC-Run perl-Test-Simple perl-Getopt-Long perl-File-Basename perl-File-Copy perl-File-Compare perl-Text-ParseWords wget unzip git pkgconf-pkg-config krb5-devel geos-devel proj-devel gdal-devel json-c-devel protobuf-c-devel sqlite-devel freetds-devel java-17-openjdk java-17-openjdk-devel libxslt-devel && dnf clean all && rm -rf /var/cache/dnf
+# 1. Установка зависимостей для сборки
+RUN dnf install -y epel-release && \
+    dnf config-manager --set-enabled crb && \
+    dnf install -y \
+        gcc gcc-c++ make flex bison \
+        libicu-devel libxml2-devel openssl-devel \
+        libuuid-devel readline-devel zlib-devel \
+        python3-devel \
+        perl perl-core perl-devel perl-IPC-Run perl-Test-Simple \
+        perl-Getopt-Long perl-File-Basename perl-File-Copy \
+        perl-File-Compare perl-Text-ParseWords \
+        wget unzip git pkgconf-pkg-config krb5-devel \
+        geos-devel proj-devel gdal-devel \
+        json-c-devel protobuf-c-devel sqlite-devel \
+        freetds-devel \
+        java-17-openjdk java-17-openjdk-devel \
+        libxslt-devel && \
+    dnf clean all && \
+    rm -rf /var/cache/dnf
 
+# 2. Java 17 для ANTLR
 ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
 ENV PATH="/usr/local/bin:${JAVA_HOME}/bin:${PATH}"
 
+# 3. Установка cmake
 WORKDIR /opt
-RUN wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh && sh cmake-${CMAKE_VERSION}-linux-x86_64.sh --skip-license --prefix=/usr/local && rm cmake-${CMAKE_VERSION}-linux-x86_64.sh
+RUN wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh && \
+    sh cmake-${CMAKE_VERSION}-linux-x86_64.sh --skip-license --prefix=/usr/local && \
+    rm cmake-${CMAKE_VERSION}-linux-x86_64.sh
 
+# 4. Клонирование репозиториев (РАЗНЫЕ теги!)
 WORKDIR /build
-RUN git clone --depth 1 --branch ${PG_BABEL_TAG} https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git && git clone --depth 1 --branch ${EXT_BABEL_TAG} https://github.com/babelfish-for-postgresql/babelfish_extensions.git
+RUN git clone --depth 1 --branch ${PG_BABEL_TAG} https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git && \
+    git clone --depth 1 --branch ${EXT_BABEL_TAG} https://github.com/babelfish-for-postgresql/babelfish_extensions.git
 
+# 5. Сборка PostgreSQL + хирургическое копирование заголовков
 WORKDIR /build/postgresql_modified_for_babelfish
-RUN ./configure --prefix=/opt/postgres --with-libxml --with-uuid=e2fs --with-icu --with-openssl --with-gssapi --disable-werror && make -j"$(nproc)" && make install && mkdir -p /opt/postgres/include/server/src/include/lib && cp src/include/lib/qunique.h /opt/postgres/include/server/src/include/lib/ && mkdir -p /opt/postgres/include/server/src/backend/utils/mb/Unicode && cp -v src/backend/utils/mb/Unicode/*.map /opt/postgres/include/server/src/backend/utils/mb/Unicode/ && cd contrib && make -j"$(nproc)" && make install
+RUN ./configure --prefix=/opt/postgres --with-libxml --with-uuid=e2fs --with-icu --with-openssl --with-gssapi --disable-werror && \
+    make -j"$(nproc)" && make install && \
+    mkdir -p /opt/postgres/include/server/src/include/lib && \
+    cp src/include/lib/qunique.h /opt/postgres/include/server/src/include/lib/ && \
+    mkdir -p /opt/postgres/include/server/src/backend/utils/mb/Unicode && \
+    cp -v src/backend/utils/mb/Unicode/*.map /opt/postgres/include/server/src/backend/utils/mb/Unicode/ && \
+    cd contrib && make -j"$(nproc)" && make install
 
 ENV PATH="/opt/postgres/bin:${PATH}"
 ENV PG_CONFIG=/opt/postgres/bin/pg_config
 
+# 6. Сборка PostGIS
 WORKDIR /build
-RUN wget -q https://download.osgeo.org/postgis/source/postgis-${POSTGIS_VERSION}.tar.gz && tar -xzf postgis-${POSTGIS_VERSION}.tar.gz && cd postgis-${POSTGIS_VERSION} && ./configure --with-pgconfig=/opt/postgres/bin/pg_config && make -j"$(nproc)" && make install && cd .. && rm -rf postgis-${POSTGIS_VERSION} postgis-${POSTGIS_VERSION}.tar.gz
+RUN wget -q https://download.osgeo.org/postgis/source/postgis-${POSTGIS_VERSION}.tar.gz && \
+    tar -xzf postgis-${POSTGIS_VERSION}.tar.gz && \
+    cd postgis-${POSTGIS_VERSION} && \
+    ./configure --with-pgconfig=/opt/postgres/bin/pg_config && \
+    make -j"$(nproc)" && make install && \
+    cd .. && rm -rf postgis-${POSTGIS_VERSION} postgis-${POSTGIS_VERSION}.tar.gz
 
+# 7. Сборка tds_fdw (для Linked Servers)
 WORKDIR /build
-RUN git clone --depth 1 --branch v${TDS_FDW_VERSION} https://github.com/tds-fdw/tds_fdw.git && cd tds_fdw && make USE_PGXS=1 PG_CONFIG=/opt/postgres/bin/pg_config -j"$(nproc)" && make USE_PGXS=1 PG_CONFIG=/opt/postgres/bin/pg_config install && cd .. && rm -rf tds_fdw
+RUN git clone --depth 1 --branch v${TDS_FDW_VERSION} https://github.com/tds-fdw/tds_fdw.git && \
+    cd tds_fdw && \
+    make USE_PGXS=1 PG_CONFIG=/opt/postgres/bin/pg_config -j"$(nproc)" && \
+    make USE_PGXS=1 PG_CONFIG=/opt/postgres/bin/pg_config install && \
+    cd .. && rm -rf tds_fdw
 
+# 8. Сборка ANTLR C++ RUNTIME (через GitHub)
 WORKDIR /build
-RUN cp /build/babelfish_extensions/contrib/babelfishpg_tsql/antlr/thirdparty/antlr/antlr-${ANTLR_VERSION}-complete.jar /usr/local/lib/ && wget -q https://github.com/antlr/antlr4/archive/refs/tags/${ANTLR_VERSION}.zip -O antlr4-source.zip && unzip -q -d antlr4 antlr4-source.zip && cd antlr4/antlr4-${ANTLR_VERSION}/runtime/Cpp && mkdir build && cd build && /usr/local/bin/cmake .. -DANTLR_JAR_LOCATION=/usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_DEMO=False -DBUILD_SHARED_LIBS=ON && make -j"$(nproc)" && make install && find /usr/local/lib /usr/local/lib64 -maxdepth 1 -name "libantlr4-runtime.so*" -exec cp {} /opt/postgres/lib/ \;
+RUN cp /build/babelfish_extensions/contrib/babelfishpg_tsql/antlr/thirdparty/antlr/antlr-${ANTLR_VERSION}-complete.jar /usr/local/lib/ && \
+    wget -q https://github.com/antlr/antlr4/archive/refs/tags/${ANTLR_VERSION}.zip -O antlr4-source.zip && \
+    unzip -q -d antlr4 antlr4-source.zip && \
+    cd antlr4/antlr4-${ANTLR_VERSION}/runtime/Cpp && mkdir build && cd build && \
+    /usr/local/bin/cmake .. -DANTLR_JAR_LOCATION=/usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_DEMO=False -DBUILD_SHARED_LIBS=ON && \
+    make -j"$(nproc)" && make install && \
+    find /usr/local/lib /usr/local/lib64 -maxdepth 1 -name "libantlr4-runtime.so*" -exec cp {} /opt/postgres/lib/ \;
 
+# 9. Подготовка к in-tree сборке: создаём симлинк /src и копируем расширения
 RUN ln -sfn /build/postgresql_modified_for_babelfish/src /src
+
 WORKDIR /build/postgresql_modified_for_babelfish/contrib
-RUN cp -r /build/babelfish_extensions/contrib/babelfishpg_money . && cp -r /build/babelfish_extensions/contrib/babelfishpg_common . && cp -r /build/babelfish_extensions/contrib/babelfishpg_tds . && cp -r /build/babelfish_extensions/contrib/babelfishpg_tsql .
+RUN cp -r /build/babelfish_extensions/contrib/babelfishpg_money . && \
+    cp -r /build/babelfish_extensions/contrib/babelfishpg_common . && \
+    cp -r /build/babelfish_extensions/contrib/babelfishpg_tds . && \
+    cp -r /build/babelfish_extensions/contrib/babelfishpg_tsql .
 
-RUN cd /build/postgresql_modified_for_babelfish/contrib/babelfishpg_tsql/antlr && /usr/local/bin/cmake . -DANTLR_JAR_LOCATION=/usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar -DJava_JAVA_EXECUTABLE=/usr/lib/jvm/java-17-openjdk/bin/java -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON && make -j"$(nproc)"
+# 10. Генерация Makefile для ANTLR в in-tree директории
+RUN cd /build/postgresql_modified_for_babelfish/contrib/babelfishpg_tsql/antlr && \
+    /usr/local/bin/cmake . -DANTLR_JAR_LOCATION=/usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar -DJava_JAVA_EXECUTABLE=/usr/lib/jvm/java-17-openjdk/bin/java -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON && \
+    make -j"$(nproc)"
 
+# 11. Сборка расширений Babelfish
 WORKDIR /build/postgresql_modified_for_babelfish/contrib/babelfishpg_money
 RUN make PG_CONFIG=/opt/postgres/bin/pg_config && make PG_CONFIG=/opt/postgres/bin/pg_config install
 
 WORKDIR /build/postgresql_modified_for_babelfish/contrib/babelfishpg_common
-RUN PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES' make PG_CONFIG=/opt/postgres/bin/pg_config && PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES' make PG_CONFIG=/opt/postgres/bin/pg_config install
+RUN PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES' make PG_CONFIG=/opt/postgres/bin/pg_config && \
+    PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES' make PG_CONFIG=/opt/postgres/bin/pg_config install
 
 WORKDIR /build/postgresql_modified_for_babelfish/contrib/babelfishpg_tds
 RUN make PG_CONFIG=/opt/postgres/bin/pg_config && make PG_CONFIG=/opt/postgres/bin/pg_config install
 
 WORKDIR /build/postgresql_modified_for_babelfish/contrib/babelfishpg_tsql
-RUN PG_CPPFLAGS='-I/usr/include -I/usr/local/include -I/usr/local/include/antlr4-runtime -DENABLE_SPATIAL_TYPES -DENABLE_TDS_LIB' SHLIB_LINK='-lsybdb -L/usr/lib64 -L/usr/local/lib -lantlr4-runtime' make PG_CONFIG=/opt/postgres/bin/pg_config && PG_CPPFLAGS='-I/usr/include -I/usr/local/include -I/usr/local/include/antlr4-runtime -DENABLE_SPATIAL_TYPES -DENABLE_TDS_LIB' SHLIB_LINK='-lsybdb -L/usr/lib64 -L/usr/local/lib -lantlr4-runtime' make PG_CONFIG=/opt/postgres/bin/pg_config install
+RUN PG_CPPFLAGS='-I/usr/include -I/usr/local/include -I/usr/local/include/antlr4-runtime -DENABLE_SPATIAL_TYPES -DENABLE_TDS_LIB' \
+    SHLIB_LINK='-lsybdb -L/usr/lib64 -L/usr/local/lib -lantlr4-runtime' \
+    make PG_CONFIG=/opt/postgres/bin/pg_config && \
+    PG_CPPFLAGS='-I/usr/include -I/usr/local/include -I/usr/local/include/antlr4-runtime -DENABLE_SPATIAL_TYPES -DENABLE_TDS_LIB' \
+    SHLIB_LINK='-lsybdb -L/usr/lib64 -L/usr/local/lib -lantlr4-runtime' \
+    make PG_CONFIG=/opt/postgres/bin/pg_config install
 
+########################################
+# Этап 2: runtime
+########################################
 FROM almalinux:9 AS runtime
-RUN dnf install -y epel-release && dnf config-manager --set-enabled crb && dnf install -y libicu libxml2 openssl libuuid krb5-libs geos proj gdal json-c protobuf-c sqlite-libs freetds glibc-langpack-en shadow-utils libstdc++ && dnf clean all && rm -rf /var/cache/dnf
 
-RUN groupadd -r postgres --gid=26 && useradd -r -g postgres --uid=26 --home-dir=/var/lib/pgsql --shell=/bin/bash postgres && mkdir -p /var/storage/pgsql/data && chown -R postgres:postgres /var/storage/pgsql
+# Runtime-зависимости
+RUN dnf install -y epel-release && \
+    dnf config-manager --set-enabled crb && \
+    dnf install -y \
+        libicu libxml2 openssl libuuid krb5-libs \
+        geos proj gdal json-c protobuf-c sqlite-libs \
+        freetds glibc-langpack-en shadow-utils \
+        libstdc++ && \
+    dnf clean all && rm -rf /var/cache/dnf
 
+# Системный пользователь БЕЗ домашней директории (правильная практика)
+# -r означает системный пользователь, домашняя директория не создаётся
+RUN groupadd -r postgres --gid=26 && \
+    useradd -r -g postgres --uid=26 --shell=/bin/bash postgres && \
+    mkdir -p /var/storage/pgsql/data && \
+    chown -R postgres:postgres /var/storage/pgsql
+
+# Копирование собранного PostgreSQL из builder-этапа
 COPY --from=builder /opt/postgres /opt/postgres
 
-# ИСПРАВЛЕНИЕ: Babelfish использует версионирование библиотек через module_pathname
-# Создаем символические ссылки для правильных имен библиотек
+# КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: Babelfish использует версионирование библиотек через module_pathname
+# Создаём символические ссылки для правильных имён библиотек
 RUN ln -s /opt/postgres/lib/babelfishpg_tsql.so /opt/postgres/lib/babelfishpg_tsql-5.so && \
     ln -s /opt/postgres/lib/babelfishpg_common.so /opt/postgres/lib/babelfishpg_common-5.so
 
+# Обновление кэша динамических библиотек ПОСЛЕ копирования файлов
 RUN ldconfig
 
-RUN if locale -a | grep -q "en_US.utf8"; then echo "✅ Locale en_US.UTF-8 is available"; else echo "❌ ERROR: en_US.UTF-8 locale not found!"; exit 1; fi
+# Проверка доступности локали
+RUN if locale -a | grep -q "en_US.utf8"; then \
+        echo "✅ Locale en_US.UTF-8 is available"; \
+    else \
+        echo "❌ ERROR: en_US.UTF-8 locale not found!"; \
+        exit 1; \
+    fi
 
 ENV PATH="/opt/postgres/bin:${PATH}"
 ENV LD_LIBRARY_PATH="/opt/postgres/lib:${LD_LIBRARY_PATH}"
@@ -73,13 +167,21 @@ ENV PGDATA=/var/storage/pgsql/data
 ENV LANG=en_US.UTF-8
 ENV LC_ALL=en_US.UTF-8
 
+# ИСПРАВЛЕНИЕ: отключаем сохранение истории psql
+# Системный пользователь postgres не имеет домашней директории,
+# поэтому перенаправляем историю psql в /dev/null
+ENV PSQL_HISTORY=/dev/null
+
 COPY entrypoint.sh /usr/local/bin/entrypoint.sh
 COPY healthcheck.sh /usr/local/bin/healthcheck.sh
 RUN chmod +x /usr/local/bin/entrypoint.sh /usr/local/bin/healthcheck.sh
 
 VOLUME ["/var/storage/pgsql/data"]
 EXPOSE 5432 1433
-HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 CMD /usr/local/bin/healthcheck.sh
+
+HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
+    CMD /usr/local/bin/healthcheck.sh
+
 USER postgres
 ENTRYPOINT ["entrypoint.sh"]
-CMD ["postgres"]
+EOF
